# Deep Learing Via ANN

Import the Library

In [2]:
import numpy as np
import pandas as pd

Import Dataset

In [6]:
df = pd.read_csv('American Express User Exit Prediction.csv')
X = df.iloc[:, 0:-1].values
y = df.iloc[:, -1].values

In [7]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [10]:
 print(y)

[0 0 0 ... 0 1 0]


# Encoding categorical Data

Gender Column : label Encoding

In [20]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
X[:, 2] = label.fit_transform(X[:, 2])

In [21]:
print(X)

[[553.0 'Delhi' 0 ... 4 1 274150]
 [447.0 'Bengaluru' 1 ... 4 1 519360]
 [501.0 'Delhi' 0 ... 4 1 545501]
 ...
 [627.0 'Mumbai' 0 ... 4 0 494067]
 [600.0 'Bengaluru' 0 ... 2 1 109375]
 [553.0 'Delhi' 1 ... 4 1 180031]]


Geography Column : one hot encoding

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [24]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


Split Dataset into training & Test set

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Implement ANN

Initialization

In [29]:
import tensorflow as tf
ANN = tf.keras.models.Sequential()

Adding input layer and first hidden layer

In [30]:
ANN.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding second hidden layer

In [32]:
ANN.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding output layer

In [33]:
ANN.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# ANN Training

Compiling ANN

In [36]:
ANN.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Training Dataset

In [37]:
ANN.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.7717 - loss: 0.6260
Epoch 2/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7955 - loss: 0.4960
Epoch 3/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7925 - loss: 0.4611
Epoch 4/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8056 - loss: 0.4289
Epoch 5/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8133 - loss: 0.4222
Epoch 6/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8194 - loss: 0.4046
Epoch 7/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8094 - loss: 0.4177
Epoch 8/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8198 - loss: 0.3929
Epoch 9/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8177 - loss: 0.3973
Epoch 10/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8152 - loss: 0.4013
Epoch 11/100
218/218 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8239 - loss: 0.3907
Epoch 12/100
218/218 ━━━━━━━━━━━━━━━━━━━━

# Predictions

Prediction on Testset

In [40]:
y_pred = ANN.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 1]]


confusion Matrix

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2258  110]
 [ 332  279]]


0.8516280631084256